// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgzculwqahdlaabzvvgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnemN1bHdxYWhkbGFhYnp2dmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTcyMTYsImV4cCI6MjA2NTA3MzIxNn0.-XMkOquxwVWqlw7uME42yfCMFXranT2s-yRKBoHab6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);